//KiwiFit Co - Gym Session Logger  
//Author: [Florence Taele]
//Date: 20/06/26 
//Status: In progress


#include <iostream>
#include <fstream>
#include <string>
#include <windows.h>

#include "tools.h"
#include "user.h"
#include "workout.h"


using namespace std;



void WelcomeScreen(){

    //Welcome Screen
    cout <<"🌴 ~ 🌱 🌴 ~ 🌱 🌴 ~ 🌱 🌴 ~ 🌱🌴 ~ 🌱 " << endl;
    cout <<" 🌿 🌿                             🥝 🥝 "<<endl;
    cout <<" 🌿 🌿         KIWIFIT-CO          🥝 🥝 "<<endl;
    cout <<" 🌿 🌿                             🥝 🥝 "<<endl;
    cout <<"🌴 ~ 🌱 🌴 ~ 🌱 🌴 ~ 🌱 🌴 ~ 🌱🌴 ~ 🌱 " << endl;
 
    cout << "               About Us              " << endl; 
    cout <<"- - - - - - - - - - - - - - - - - - - - "<< endl;
    cout<<"Welcome to Kiwifit-Co, proudly created in New Zealand for everyone at any age!"<<endl;
    cout<<"About: The purpose of this mini-app generated by C++, is to be able to help kiwi's track their fitness Goals!"<<endl;
    
    pauseScreen();
    clearScreen();
}

void MainMenu(){
        setlocale(LC_ALL, "en_US.UTF-8");  //enable emjois/unicode

    while(true){
        int user_input; 

        cout <<" --- Main Menu ---"<<endl;

        cout <<"1. 👤 User Menu"<<endl;
        cout <<"2. 💪 Workout Menu"<<endl;
        cout <<"3. 🚪 Exit"<<endl;

        cout <<"Enter your preferred choice (1-8)"<<endl;
        cin >> user_input;

        if (user_input == 1){
            User_Menu();
        }else if (user_input == 2){
            workoutMenu();
        } else if(user_input == 3){
            cout <<"Thank you for using our service!"<<endl;
            break;
        } 
        else {
            cout <<"🔴Closing Program..."<<endl;
            break;
        }

    }
    
}

void Register(){
    string name, last_name;
    int age;
}

int main() { 

    SetConsoleOutputCP(CP_UTF8);

    WelcomeScreen();
    MainMenu();

    return 0;
}